### ISSUE TITLE
# of dataset counted/shown incorrectly

### ISSUE THREAD

**Issue by SigritSiht** [okestonia/opendata.riik.ee#620]
https://opendata.riik.ee/et/orgs/tartu-linnavalitsus/ only has 7 datasets but 24 is printed.
Also 24 Andmehulgad is grammatically incorrect, I don't really know the full logic behind your code but the easiest fix would be "Andmehulkade arv: <# of datasets>".

**Comment by keeganmcbride** [comment]
The 7 datasets is a bug, thanks for pointing it out! I will fix shortly.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by keeganmcbride** [comment]
Fixed in: https://github.com/okestonia/opendata.riik.ee/commit/fc872e1efd2c4018c4faf6154f9cea922bec0a3a

**Comment by keeganmcbride** [comment]
Both issues should be fixed now.

**Comment by SigritSiht** [comment]
> Both issues should be fixed now.

The grammatical error bug is partially fixed, if I use the search bar and type anything there it goes back to the original one.

**Comment by keeganmcbride** [comment]
Ahh, thanks again. Will push a fix out now.

**Comment by keeganmcbride** [comment]
@SigritSiht can you close once you have confirmed this is now fixed?

**Comment by SigritSiht** [comment]
Tested, everything works, closing current issue
